export default{
    id : 0,
    userTypeId : 0,
    userGuid:'',
    name:'',
    surname:'',
    email:'',
    password:'',
    identityNr:'',
    gender:0,
    birthDate:new Date().toJSON().slice(0,10),
    jobId : 0,
    countryId : 0,
    cityId:0,
    avatarPath:'',
    phoneNr:'',
    taxNr:'',
    eventCount:0,
    emailVerification:1,
    profileStatus:1,
    notificationStatus:1,
    avatarFile :[],
    creatorId:0,
    creationDate : new Date().toJSON().slice(0,10),
    statusId : 2
}